### PR TITLE
Add getVolume function

### PR DESCRIPTION
**Pull request by haydenw**
See example here https://gist.github.com/haydenw/a7a0fd4c3701ae46fbc4. Or am I doing it wrong?

### CODE REVIEW

**Comment by elliotchance** [comment]
`OrderBook::getBuyOrders()` returns `SimpleOrder[]` and `SimpleOrder` has a `getVolume()` method:
 https://github.com/elliotchance/independentreserve/blob/master/src/IndependentReserve/Object/SimpleOrder.php#L27

Please try this:

``` php
foreach ($orderBook->getBuyOrders() as $buyOrder) {
    var_dump($buyOrder);
}
```

And paste the output.

**Comment by haydenw** [comment]
It appears to be returning an `IndependentReserve\Object\Order` object. Here is a dump of first object it returned:

```
object(IndependentReserve\Object\Order)#126 (1) {
  ["object":protected]=>
  object(stdClass)#17 (3) {
    ["OrderType"]=>
    string(8) "LimitBid"
    ["Price"]=>
    float(283.16)
    ["Volume"]=>
    float(1.52)
  }
}
```

Cheers

**Comment by elliotchance** [comment]
I had a feeling that's what it was. Yes it's a bug, here are the bad tests:

https://github.com/elliotchance/independentreserve/blob/master/tests/unit/IndependentReserve/Object/OrderBookTest.php#L85

It should read:

``` php
$this->assert($buyOrders[0], instance_of, '\IndependentReserve\Object\SimpleOrder');
```

Which would fail because:

https://github.com/elliotchance/independentreserve/blob/master/src/IndependentReserve/Object/OrderBook.php#L50

Is supposed to be:

``` php
return SimpleOrder::createFromObject($object);
```

I will release a new version today.

**Comment by elliotchance** [comment]
Fixes in https://github.com/elliotchance/independentreserve/pull/10

There is a v1.1.1 out, please update your composer and let me know if you run into any further issues.

**Comment by haydenw** [comment]
Awesome, thanks for that.

I think that the packagist listing needs to be updated to v1.1.1 so I can composer update to next version https://packagist.org/packages/elliotchance/independentreserve

**Comment by elliotchance** [comment]
Auto update is not enabled even though I have the github hook setup... Anyway, I've updated it manually.

**Comment by haydenw** [comment]
All good now - thanks

**Pull request closed without merging**
