### PR TITLE
Litecoin support

### PR DESCRIPTION
**Pull request by jasonbphillips**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/independentreserve/15)

### CODE REVIEW

**Comment by elliotchance** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tests/integration/IndependentReserve/ClientIntegrationPublicTest.php, line 29 at r1](https://beta.reviewable.io/reviews/elliotchance/independentreserve/15#-LAfDoek3R1Tf4ikgAgo:-LAfDoel2fc4wnc7iX4y:bv2qmo3) ([raw file](https://github.com/elliotchance/independentreserve/blob/e418e853d6cf52f293efde73bba6495bfdf8e54b/tests/integration/IndependentReserve/ClientIntegrationPublicTest.php#L29)):*
> ```PHP
>     {
>         $currencyCodes = $this->client->getValidSecondaryCurrencyCodes();
>         #$this->assert($currencyCodes, has_value, Currency::USD);
> ```

Please remove this line.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/independentreserve/15)*

**Comment by jasonbphillips** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/IndependentReserve/ClientIntegrationPublicTest.php, line 29 at r1](https://beta.reviewable.io/reviews/elliotchance/independentreserve/15#-LAfDoek3R1Tf4ikgAgo:-LAgXhtr2rePFzrXaepD:b-896fix) ([raw file](https://github.com/elliotchance/independentreserve/blob/e418e853d6cf52f293efde73bba6495bfdf8e54b/tests/integration/IndependentReserve/ClientIntegrationPublicTest.php#L29)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary><blockquote>

Please remove this line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/independentreserve/15)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/elliotchance/independentreserve/15)*

**Comment by elliotchance** [comment]
Thanks @jasonbphillips, I have released v1.1.4.

**Comment by jasonbphillips** [comment]
(thumbs up)

**Pull request merged**
